name: alignment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - font-ttf-dejavu-sans-mono=2.37
  - gatk4=4.1.7.0
  - multiqc=1.9
  - qualimap=2.2.2d
  - sambamba=0.7.1
  - samtools=1.9 #1.10 conflicts with sambamba 0.7.1
  - samblaster=0.1.26
  - bwa=0.7.17
  - bwakit=0.7.15
  - r-data.table=1.12.8
  - r-dplyr=1.0.0
  - r-ggplot2=3.3.2
  - r-gplots=3.0.3
  - r-gsalib=2.1.0
  - adapterremoval=2.3.1
  - bazam=1.0.1
  - bwa-mem2=2.1
